export const mockThreats = [
  {
    id: 1,
    type: 'phishing',
    url: 'fake-bank-login.com',
    description: '은행 로그인 페이지 위장',
    time: '14:32',
    riskLevel: 'high',
  },
  {
    id: 2,
    type: 'phishing',
    url: 'paypal-verify.xyz',
    description: 'PayPal 계정 확인 요구',
    time: '13:48',
    riskLevel: 'medium',
  },
  {
    id: 3,
    type: 'phishing',
    url: 'update-security-info.com',
    description: '보안 정보 업데이트 유도',
    time: '12:55',
    riskLevel: 'medium',
  },
  {
    id: 4,
    type: 'phishing',
    url: 'nid.naver-login-check.cc',
    description: '네이버 아이디 보호조치 해제 위장',
    time: '11:20',
    riskLevel: 'high',
  },
  {
    id: 5,
    type: 'phishing',
    url: 'coupang-delivery-change.info',
    description: '택배 주소지 변경 요청 피싱',
    time: '10:15',
    riskLevel: 'medium',
  },
  {
    id: 6,
    type: 'phishing',
    url: 'google-security-alert.net',
    description: '구글 계정 비정상 로그인 알림 위장',
    time: '09:40',
    riskLevel: 'high',
  },
  {
    id: 7,
    type: 'phishing',
    url: 'kakaobank-loan-support.biz',
    description: '카카오뱅크 정부지원 대출 사칭',
    time: '09:10',
    riskLevel: 'high',
  },
  {
    id: 8,
    type: 'phishing',
    url: 'apple-id-lock-fix.com',
    description: 'Apple ID 잠금 해제 요청',
    time: '08:55',
    riskLevel: 'medium',
  },
  {
    id: 9,
    type: 'phishing',
    url: 'netflix-payment-failed.org',
    description: '넷플릭스 결제 정보 갱신 유도',
    time: '어제',
    riskLevel: 'medium',
  },
  {
    id: 10,
    type: 'phishing',
    url: 'post-office-tracking.net',
    description: '우체국 택배 반송 안내 문자',
    time: '어제',
    riskLevel: 'medium',
  },
  {
    id: 11,
    type: 'phishing',
    url: 'facebook-copyright-violation.support',
    description: '페이스북 저작권 위반 경고',
    time: '어제',
    riskLevel: 'high',
  },
  {
    id: 12,
    type: 'phishing',
    url: 'work-document-sign.pdf.exe',
    description: '업무 문서 위장 악성코드 유포',
    time: '어제',
    riskLevel: 'high',
  },

  {
    id: 13,
    type: 'scam',
    url: 'win-prize-now.net',
    description: '가짜 경품 당첨 사이트',
    time: '14:15',
    riskLevel: 'high',
  },
  {
    id: 14,
    type: 'scam',
    url: 'free-crypto-giveaway.io',
    description: '암호화폐 무료 지급 사기',
    time: '13:22',
    riskLevel: 'high',
  },
  {
    id: 15,
    type: 'scam',
    url: 'invest-guaranteed-return.biz',
    description: '고수익 보장 투자 사기',
    time: '12:10',
    riskLevel: 'high',
  },
  {
    id: 16,
    type: 'scam',
    url: 'urgent-family-help.sms',
    description: '자녀 사칭 금전 요구(메신저 피싱)',
    time: '11:45',
    riskLevel: 'high',
  },
  {
    id: 17,
    type: 'scam',
    url: 'lotto-winning-number.vip',
    description: '로또 당첨 번호 예측 사이트',
    time: '10:30',
    riskLevel: 'medium',
  },
  {
    id: 18,
    type: 'scam',
    url: 'romance-meet-lover.xyz',
    description: '로맨스 스캠 유도 데이팅 사이트',
    time: '09:50',
    riskLevel: 'medium',
  },
  {
    id: 19,
    type: 'scam',
    url: 'stock-vip-group-invite.chat',
    description: '주식 리딩방 VIP 초대 문자',
    time: '08:20',
    riskLevel: 'high',
  },
  {
    id: 20,
    type: 'scam',
    url: 'donation-charity-fake.org',
    description: '가짜 자선 단체 기부금 모집',
    time: '어제',
    riskLevel: 'medium',
  },
  {
    id: 21,
    type: 'scam',
    url: 'illegal-gambling-site.bet',
    description: '불법 도박 사이트 홍보',
    time: '어제',
    riskLevel: 'high',
  },
  {
    id: 22,
    type: 'scam',
    url: 'free-gift-card-survey.com',
    description: '설문조사 위장 개인정보 탈취',
    time: '어제',
    riskLevel: 'medium',
  },
  {
    id: 23,
    type: 'scam',
    url: 'used-item-fraud-market.cafe',
    description: '중고거래 사기 의심 사이트',
    time: '어제',
    riskLevel: 'medium',
  },
  {
    id: 24,
    type: 'scam',
    url: 'voice-phishing-gov.call',
    description: '검찰청 사칭 보이스피싱 연동',
    time: '2일 전',
    riskLevel: 'high',
  },
];
